mysql:
  host: localhost
  port: 3306
  database: test
  username: root
  password: ""

time-remaining:
  value:

selling-item:
  type: vanilla # vanilla or custom or both | Custom will identify based on model-data and vanilla will identify based on material
  material: STICK
  name: "&eSelling Item"
  lore:
    - "&7Use this item to sell the contents of a chest directly"
    - "&7to the hoarder. Right-click the chest with this item"
  glow: true
  model-data: 9999
