title: "&7Hoarder &8| &eSettings Editor"

layout:
  - "b b b b b b b b b"
  - "b . s . e . r . b"
  - "b . . w . f . . b"
  - "i b b b c b b b b"

items:
  i:
    type: PLAYER_HEAD
    skull-hash: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGM0ZTQ0MWVhYzg4NGRlMzM0N2E4Nzc1YTA3YTY2YmJjNGM4MmEyNGVkMmQwY2ZlYjFhY2FmNmNlOTlkNTNiNiJ9fX0="
    name: "&cInformation"
    lore:
      - "&7This menu handles hoarder's settings"
      - "&7You can change the event time, starting time, random material and white-listed items"
      - "&7You can also change the fixed item"
      - "&7You can close this menu by clicking the &cClose &7item"
  b:
    type: BLACK_STAINED_GLASS_PANE
    name: " "
    lore:
      - " "
  w:
    type: WHITE_CONCRETE
    name: "&7White-listed Items"
    lore:
      - "&7Left-Click to open the white-listed items editor"
  f:
    type: STONE
    name: "&7Fixed Item"
    lore:
      - "&7Left-Click change the fixed item"
  r:
    type: NETHER_STAR
    name: "&7Random Material"
    lore:
      - "&7Click to enable/disable random material"
      - "&7Value: %random-material%"
  e:
    type: CLOCK
    name: "&7Event Time"
    lore:
      - "&7Left-Click to change the event time"
      - "&7Current time: %event-time%"
  s:
    type: CLOCK
    name: "&7Starting Time"
    lore:
      - "&7Left-Click to change the starting time"
      - "&7Current time: %starting-time%"
  item:
    type: PAPER
    name: "&%setting%"
    lore:
      - "&7Left-Click to change the setting"
  c:
    type: PLAYER_HEAD
    skull-hash: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmViNTg4YjIxYTZmOThhZDFmZjRlMDg1YzU1MmRjYjA1MGVmYzljYWI0MjdmNDYwNDhmMThmYzgwMzQ3NWY3In19fQ=="
    name: "&cClose"
    lore:
      - "&7Click to close the menu."
